start_session:
  fields:
    name:
      required: true
      example: Northern Brown Ale
      selector:
        text:
    recipe_url:
      example: https://example.com/recipe
      selector:
        text:
    og:
      example: 1.0595
      selector:
        number:
          min: 0.98
          max: 1.2
          step: 0.0001
          mode: box
    pitched:
      selector:
        datetime:

end_session:
  fields:
    fg:
      example: 1.012
      selector:
        number:
          min: 0.98
          max: 1.2
          step: 0.0001
          mode: box

delete_session:
  fields:
    session_id:
      required: true
      selector:
        text:
